/* Catalogue des guides — rotation saisonnière (les fichiers HTML restent en ligne) */
window.JEUXSTASH_GUIDES = [
  {
    id: "black-friday-jeux-2026",
    href: "/guides/black-friday-jeux-2026",
    title: "Black Friday jeux 2026",
    blurb: "Dates, liste courte et méthode pour ne pas paniquer le jour J.",
    kicker: "Soldes",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/2379780/header.jpg",
    evergreen: true,
    seasons: ["automne", "hiver"],
  },
  {
    id: "meilleurs-jeux-pas-cher-automne-2026",
    href: "/guides/meilleurs-jeux-pas-cher-automne-2026",
    title: "Meilleurs jeux — automne 2026",
    blurb: "Huit idées pour la rentrée, avec où comparer le prix.",
    kicker: "Saison",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/1030300/header.jpg",
    evergreen: true,
    seasons: ["automne", "hiver"],
  },
  {
    id: "call-of-duty-pas-cher",
    href: "/guides/call-of-duty-pas-cher",
    title: "Black Ops 7 & MW4 : où acheter",
    blurb: "Battle.net ou Xbox, précommande MW4, Vault ou Standard.",
    kicker: "COD",
    thumb: "https://gaming-cdn.com/images/products/16809/616x353/call-of-duty-modern-warfare-4-xbox-series-x-s-pc-microsoft-store-cover.jpg",
    evergreen: true,
    seasons: ["automne", "hiver"],
  },
  {
    id: "gta-6-pas-cher",
    href: "/guides/gta-6-pas-cher",
    title: "GTA 6 : précommande PC",
    blurb: "Consoles d’abord, PC ensuite — ce qu’il faut anticiper.",
    kicker: "GTA",
    thumb: "https://gaming-cdn.com/images/products/2462/616x353/grand-theft-auto-vi-pc-cover.jpg",
    evergreen: true,
    seasons: ["automne", "hiver", "ete"],
  },
  {
    id: "ea-fc-pas-cher",
    href: "/guides/ea-fc-pas-cher",
    title: "FC 27 moins cher : racheter ?",
    blurb: "Prix Instant Gaming, Standard ou Deluxe, quand attendre.",
    kicker: "Sport",
    thumb: "https://gaming-cdn.com/images/products/21656/616x353/ea-sports-fc-27-pc-ea-app-cover.jpg",
    evergreen: true,
    seasons: ["ete", "automne"],
  },
  {
    id: "disco-elysium-pas-cher",
    href: "/guides/disco-elysium-pas-cher",
    title: "Disco Elysium Instant Gaming",
    blurb: "Prix, Final Cut, faut-il acheter maintenant.",
    kicker: "RPG",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/632470/header.jpg",
    evergreen: true,
    seasons: ["automne", "hiver", "printemps"],
  },
  {
    id: "far-cry-5-pas-cher",
    href: "/guides/far-cry-5-pas-cher",
    title: "Far Cry 5 PC pas cher",
    blurb: "Ubisoft Connect, prix IG, quand comparer.",
    kicker: "Action",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/552520/header.jpg",
    evergreen: true,
    seasons: ["automne", "hiver", "ete"],
  },
  {
    id: "elden-ring-pas-cher",
    href: "/guides/elden-ring-pas-cher",
    title: "Elden Ring : Standard ou DLC",
    blurb: "Base seule, pack Erdtree, et comment ne pas surpayer.",
    kicker: "RPG",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg",
    evergreen: true,
    seasons: ["hiver", "automne"],
  },
  {
    id: "black-myth-wukong-pas-cher",
    href: "/guides/black-myth-wukong-pas-cher",
    title: "Wukong : où l’acheter",
    blurb: "Clé Steam, IG vs store, pour qui c’est fait.",
    kicker: "Action",
    thumb: "https://gaming-cdn.com/images/products/7678/616x353/black-myth-wukong-pc-steam-cover.jpg",
    evergreen: true,
    seasons: ["automne", "hiver", "ete"],
  },
  {
    id: "expedition-33-pas-cher",
    href: "/guides/expedition-33-pas-cher",
    title: "Expedition 33 : prix & édition",
    blurb: "RPG acclamé — compare avant le plein tarif.",
    kicker: "RPG",
    thumb: "https://gaming-cdn.com/images/products/17015/616x353/clair-obscur-expedition-33-pc-steam-cover.jpg",
    seasons: ["automne", "hiver", "printemps"],
  },
  {
    id: "instant-gaming-fiable",
    href: "/guides/instant-gaming-fiable",
    title: "Instant Gaming fiable ? Avis 2026",
    blurb: "Clés, risques, quand acheter sans se faire avoir.",
    kicker: "Avis",
    evergreen: true,
  },
  {
    id: "acheter-jeux-pas-cher",
    href: "/guides/acheter-jeux-pas-cher",
    title: "Jeux pas cher : 3 règles",
    blurb: "Attendre, comparer, n’acheter que ce soir.",
    kicker: "Budget",
    evergreen: true,
  },
  {
    id: "cles-jeux-legitimes",
    href: "/guides/cles-jeux-legitimes",
    title: "Clés de jeux : ce qu’il faut vérifier",
    blurb: "Repérer les risques avant le paiement.",
    kicker: "Sécurité",
    evergreen: true,
  },
  {
    id: "forza-horizon-5-pas-cher",
    href: "/guides/forza-horizon-5-pas-cher",
    title: "Forza 5 : IG ou Game Pass",
    blurb: "Achat vs abo — le calcul simple.",
    kicker: "Course",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg",
    seasons: ["ete", "printemps"],
  },
  {
    id: "soldes-steam-payer-moins",
    href: "/guides/soldes-steam-payer-moins",
    title: "Soldes Steam",
    blurb: "Utiliser la wishlist sans se précipiter.",
    kicker: "Soldes",
    evergreen: true,
  },
  {
    id: "cle-steam-pas-cher",
    href: "/guides/cle-steam-pas-cher",
    title: "Clés Steam sans se faire avoir",
    blurb: "Où acheter, quoi vérifier sur la fiche.",
    kicker: "Clés",
    evergreen: true,
  },
  {
    id: "baldurs-gate-3-pas-cher",
    href: "/guides/baldurs-gate-3-pas-cher",
    title: "Baldur’s Gate 3 : quand acheter",
    blurb: "GOG / Instant Gaming, timing des baisses.",
    kicker: "RPG",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg",
    seasons: ["hiver", "automne"],
  },
  {
    id: "cyberpunk-pas-cher",
    href: "/guides/cyberpunk-pas-cher",
    title: "Cyberpunk : quelle édition",
    blurb: "Standard vs Ultimate — ce qui change vraiment.",
    kicker: "RPG",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg",
    seasons: ["hiver", "automne"],
  },
  {
    id: "jeux-ce-soir-pas-cher",
    href: "/guides/jeux-ce-soir-pas-cher",
    title: "Quoi jouer ce soir",
    blurb: "6 idées + liens prix.",
    kicker: "Idées",
    seasons: ["printemps", "ete"],
  },
  {
    id: "game-pass-vs-acheter",
    href: "/guides/game-pass-vs-acheter",
    title: "Game Pass ou acheter",
    blurb: "Le calcul en 30 secondes.",
    kicker: "Choix",
    seasons: ["hiver", "printemps"],
  },
  {
    id: "meilleurs-jeux-coop-2026",
    href: "/guides/meilleurs-jeux-coop-2026",
    title: "Jeux coop",
    blurb: "Quoi lancer à deux.",
    kicker: "Coop",
    thumb: "https://cdn.cloudflare.steamstatic.com/steam/apps/1426210/header.jpg",
    seasons: ["printemps", "ete"],
  },
  {
    id: "pc-gaming-petit-budget",
    href: "/guides/pc-gaming-petit-budget",
    title: "PC petit budget",
    blurb: "Où mettre l’argent.",
    kicker: "PC",
    seasons: ["ete", "automne"],
  },
  {
    id: "meilleurs-jeux-sport-2026",
    href: "/guides/meilleurs-jeux-sport-2026",
    title: "Jeux de sport",
    blurb: "Faut-il racheter chaque année ?",
    kicker: "Sport",
    thumb: "https://gaming-cdn.com/images/products/21656/616x353/ea-sports-fc-27-pc-ea-app-cover.jpg",
    seasons: ["ete", "automne"],
  },
];
